### ISSUE TITLE
Jaro-Winkler distance name matcher

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#10]
~~- [ ] Port this Java implementation into Python: https://github.com/fbk/utils/blob/master/utils-core/src/main/java/eu/fbk/utils/core/strings/JaroWinklerDistance.java
based on Apache Commons lang: https://commons.apache.org/proper/commons-text/javadocs/api-release/index.html?org/apache/commons/text/similarity/JaroWinklerDistance.html
original source code should be contained here: http://it.apache.contactlab.it//commons/lang/source/commons-lang3-3.7-src.tar.gz;~~
- [ ] use [jellyfish](https://github.com/jamesturk/jellyfish);
- [ ] for each full name of a target identifier, compute the Jaro-Winkler edit distance against all Wikidata item labels.

**Comment by MaxFrax** [comment]
Penso che esista già:
https://github.com/nap/jaro-winkler-distance

**Comment by marfox** [comment]
_Jellyfish_ also contains other edit distances implementations, Levenshtein included.
It is also useful for #9
