### ISSUE TITLE
Birth and death dates matcher

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#11]
For each _(birth, death)_ couple (_death_ is optional) of a target identifier, for each of [#6, #9, #10], match against Wikidata item birth and death dates, and labels.

**Comment by marfox** [comment]
Mix'n'match approach here: https://bitbucket.org/magnusmanske/mixnmatch/src/583070219aea573bdcd9ff7b2884c2a1193b1ed3/scripts/match_person_entries_by_name_and_dates.php?at=master&fileviewer=file-view-default

**Comment by marfox** [comment]
Should be implemented here:
https://github.com/Wikidata/soweego/blob/master/soweego/target_selection/commons/matching_strategies.py

**Comment by MaxFrax** [comment]
While comparing the dates of two entities, they are a match only if both the birth and the death dates are equal.
However, if two dates have different precisions, they are a match if the available information is equal.
E.g. 2019/02 matches with 2019/02/28, but not with 2019/01/28

Taking into account the latest project developments, this functionality must be both a function available to the other developers and an option for the perfect/similar names CLI.
