### ISSUE TITLE
Find out if 'camera_department' is represented in Wikidata

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#162]
The `camera_department` profession is well represented in IMDb, with more than **560k** occurrences.
Try to find the best mapping to Wikidata, then count the occurrences there.

**Comment by tupini07** [comment]
According to [this page](https://help.imdb.com/article/contribution/filmography-credits/camera-department/GE2LSX8GL65XL5TC?ref_=helpms_helpart_inline#), the `camera_department` contains those jobs related with camera handling, [grip](https://en.wikipedia.org/wiki/Grip_(job)), phtography, and camera related electrician. Basically, all those camera related jobs that don't have their own category.

I checked the camera department related jobs of _300_ random people who had `camera_department` in their list of primary occupations, and these are the most common jobs I found:

![figure_1](https://user-images.githubusercontent.com/3422347/52787608-b009c480-305e-11e9-90b5-20e65f0b87ef.png)

We can see that `camera operator` is the most common one, followed by `assistant camera`, `grip`,  and `still photographer`.

By using the folllowing query on [https://query.wikidata.org](https://query.wikidata.org) 

    SELECT (COUNT(DISTINCT ?item) AS ?total) WHERE { ?item (wdt:P106/wdt:P279*) wd:QID. }

I was able to find the QIDs and occurrences of them in Wikidata. Results below:

| Occupation | Wikidata QID | Occurrences in Wikidata |
| --- | --- | ---|
| Camera Operator | Q1208175 | 8551|
| Assistant Camera | Q1639269 | 2 | 
| Grip | Q3274496 | 2 |
| Still Photographer | Q20743434 | 22 |
| Electrician (general occupation) | Q165029 | 144 |
| Gaffer | Q1424726 | 5 |
| Key Grip | Q1547003 | 7 |
| Lighting Technician | Q17082153 | 0 |
| Videographer | Q3766177 | 1915 |

Based on the above, I would say that it is safe to map the `camera_department` profession with the `Camera Operator (Q1208175)` Wikidata occupation.

@marfox @MaxFrax , do you think this can be a good idea?

**Comment by marfox** [comment]
Great work, @tupini07 , that totally makes sense.
Closing this with the outcome:
`camera_department` -> `Q1208175`
