### ISSUE TITLE
Cluster professions related to music in IMDb

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#164]
The following professions are well represented in IMDb:
1. `sound_department` (285k occurrences);
2. `composer` (222k);
3. `music_department` (172k);
4. `soundtrack` (122k).

`composer` is quite well represented in Wikidata as well (96k occurrences).

Find out if we can cluster the above 4 professions into one generic Wikidata class (perhaps `musician`?)

This would be the 5th entity/table in our database.

**Comment by tupini07** [comment]
The IMDB documentation pages defines these 4 classes as disjoint.

[This page](https://help.imdb.com/article/contribution/filmography-credits/composers/GFLLMYE6VJUXBYJT?ref_=helpms_helpart_inline#) defines `composers` as persons who compose only the _main background score_ and not music which appears in a movie/tv-episode (those are part of `soundtrack`). Typically, a film or tv-show only have **one eligible composer**.

[This page](https://help.imdb.com/article/contribution/titles/soundtracks/GKD97LHE9TQ49CZ7?ref_=helpms_helpart_inline#) defines the `soundtrack` as the music which appears as part of a film/tv-show. A person with this profession is either the _writer_ of the piece or the _performer_.

[This page](https://help.imdb.com/article/contribution/filmography-credits/music-department/G9QPJV4FV85BRM7X?ref_=helpart_nav_37#) defines `music department` as the list of jobs which includes all _musical_ jobs not already covered by the `composer` or `soundtrack` lists. If a person appears in the `composer` or `soundtrack` list for a specific film then he/she won't appear as part of the `music department`.  Basically, the sound department is composed of the following:

- Musicians (performers)
- Orchestrators
- Music contractors
- Arrangers
- Additional Composers
- All credits related to recording and mixing music.
- Any music-related credits except composer (songs by, lyricist, singer, musician, arranger, song or music producer, etc.) 

Finally, [this page](https://help.imdb.com/article/contribution/filmography-credits/sound-department/GVVM7V4DW4UPADYJ?ref_=helpms_helpart_inline#) defines `sound department` as the one which includes any _sound related job_ that is not already covered by the previous 3 (`composer`, `soundtrack`, and `music department`). It does not include the writing or playing of music. People in the `sound department` are the ones in charge of recording audio for the film/tv-episode and for the sound effects. 

Based on the above, I think we could safely cluster the first 3 (`composer`, `soundtrack`, and `music department`) under `musician`. But I'm not so sure about the `sound department`; that sounds more like it should be `Audio Engineer (Q128124)` or even `Sound Editor (Q3180462)` or `Production Sound Mixer (Q2961972)`. @marfox, what do you think?

**Comment by marfox** [comment]
> Based on the above, I think we could safely cluster the first 3 (`composer`, `soundtrack`, and `music department`) under `musician`.

Totally agree, please go ahead.

> But I'm not so sure about the `sound department`; that sounds more like it should be `Audio Engineer (Q128124)` or even `Sound Editor (Q3180462)` or `Production Sound Mixer (Q2961972)`. @marfox, what do you think?

To answer this, run the following query, which counts Wikidata items having these classes as value of `occupation`:
```
SELECT (COUNT(DISTINCT ?item) AS ?total) WHERE { ?item wdt:P106/wdt:P279* wd:QID_HERE }
```
1. `Audio Engineer (Q128124)`: **13,436**;
2. `Sound Editor (Q3180462)`: **86**;
3. `Production Sound Mixer (Q2961972)`: **22**.

Based on this evidence, it **may** make sense to **use `Q128124`** .

**Comment by marfox** [comment]
> Based on this evidence, it **may** make sense to **use `Q128124`** .

Based on the first 20 results of the above query, this class seems to be often intersected with `musician`, so I suggest to:
1. cluster it under `musician` anyway, i.e., 5th table of our DB;
2. use `Q128124` in the `occupation` column of the table.
