### ISSUE TITLE
Segmentation fault when training in Docker container

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#166]
The same command works with `pipenv` and **segfaults** in the Docker container, i.e.,
```
pipenv run python -m soweego linker train nb discogs musician
```
works fine.

Steps to reproduce from the project root directory:
```bash
./scripts/docker/launch_test.sh
cd soweego
python -m soweego linker train nb discogs musician
```

The segfault happens when the following line of `linker/workflow.py#_preprocess_target` is executed:
```py
    target = concat([chunk for chunk in target_reader],
                    ignore_index=True, sort=False)
```

After a preliminary digging, this seems to most similar issue:
https://stackoverflow.com/a/54284013/10719765

Related to #146

**Comment by marfox** [comment]
Slightly different Python versions used:
- pipenv: 3.7.**2**
- Docker test: 3.7.**0**

**Comment by marfox** [comment]
> @marfox it all happened in your laptop, didn't it?

Yes

**Comment by marfox** [comment]
@MaxFrax : please place these files in `/app/shared`:
[wikidata_discogs_training_set.jsonl.gz](https://github.com/Wikidata/soweego/files/2832569/wikidata_discogs_training_set.jsonl.gz)
[discogs_training_set.jsonl.gz](https://github.com/Wikidata/soweego/files/2832575/discogs_training_set.jsonl.gz)

**Comment by marfox** [comment]
Hardware configuration of the machine that hits this bug:
![screen shot 2019-02-05 at 16 51 07](https://user-images.githubusercontent.com/4838312/52285327-6d613180-2966-11e9-8b99-14409ca1411a.png)

**Comment by MaxFrax** [comment]
On my machine, with less RAM, I cannot reproduce the bug.
Also on the Wikimedia Foundation VPS works.
