### ISSUE TITLE
While importing discogs soweego occurs a fatal disconnection

### ISSUE THREAD

**Issue by MaxFrax** [Wikidata/soweego#179]
`sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query') (Background on this error at: http://sqlalche.me/e/e3q8)`

We have decided to fix this issue by handling the disconnection explicitly.
The resulting behaviour will be that after a disconnection, soweego reconnects and restarts from where it left.

It's a good time to let the pipeline write the logs in the shared folder. (`launch_pipeline.sh`).

**Notes**:
Interesting docs to get started https://docs.sqlalchemy.org/en/rel_1_2/core/pooling.html#dealing-with-disconnects .

**Comment by marfox** [comment]
Max **20** connections per user: https://phabricator.wikimedia.org/T216170
