### ISSUE TITLE
Launch Naïve Bayes and SVM linkers over complete MusicBrainz datasets

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#203]
INPUT: artist dataset, band dataset
- [x] evaluate;
- [x] train;
- [x] classify;
- [x] track progress & report. 

Corresponding CLI command examples:
```
python -m soweego linker evaluate nb musicbrainz artist
python -m soweego linker train nb musicbrainz artist
python -m soweego linker classify musicbrainz artist /app/shared/musicbrainz_nb_model.pkl
```

**Comment by MaxFrax** [comment]
@marfox is there a way to avoid the model as an argument? A working default value would be enough

**Comment by marfox** [comment]
I didn't put a default value because we can have models trained with different algorithms.

**Comment by marfox** [comment]
Said that, we can always set a reasonable default

**Comment by MaxFrax** [comment]
@marfox If I execute the following commands, which name will the file have?
```
python -m soweego linker evaluate nb musicbrainz artist
python -m soweego linker train nb musicbrainz artist
```

**Comment by marfox** [comment]
`musicbrainz_nb_model.pkl`.
BTW, the entity is missing and should be added to the file name.

**Comment by MaxFrax** [comment]
What do you mean for `track progress & report` in the issue description?

**Comment by marfox** [comment]
Write down notes, issues, etc. for reporting purposes

**Comment by MaxFrax** [comment]
Report

All commands launched on soweego-2 VPS instance;
all I/O files and logs at **TO DO**.
Musician

Evaluation

Precision:
mean =  0.9444080077302754
standard deviation = 0.00157738637718051
Recall:
mean = 0.8551912065571845
standard deviation = 0.002603810311224934
F-score:
mean = 0.8975842104582478
standard deviation = 0.001220089005321426
Training - **TO DO**

python -m soweego -l soweego DEBUG linker train nb discogs musician
log file: 20190325_discogs_musician_training_set.log.bz2
Wikidata dataset: 58,233 items with Discogs ids (117 buckets of 500 items), gathered in 1 h 41 min
model: discogs_musician_nb_model.pkl, 1.7 KB
Classification

python -m soweego -l soweego DEBUG linker classify discogs musician ../shared/discogs_musician_nb_model.pkl
log file: 20190325_discogs_musician_classification_set.log.bz2
Wikidata dataset: 199,181 items, gathered in 4 h 21 min
total predictions: 67,821 (39,343 unique), threshold = 0.5 (default)
Band

Evaluation

Precision:
mean = 0.7401669337112958
standard deviation = 0.011077718306240904
Recall:
mean = 0.2169744484660759
standard deviation = 0.0057991133073990765
F-score:
mean = 0.33554334708267425
standard deviation = 0.007503993845358352
Training

python -m soweego -l soweego DEBUG linker train nb discogs band
log file: 20190325_discogs_band_training_set.log.bz2
Wikidata dataset: 26,550 items with Discogs ids (54 buckets of 500 items)
model: discogs_band_nb_model.pkl, 1.7 KB
Classification

python -m soweego -l soweego DEBUG linker classify discogs band ../shared/discogs_band_nb_model.pkl
log file: 20190325_discogs_band_classification_set.log.bz2
Wikidata dataset: 50,317 items, gathered in 1 min 42 sec
total predictions: 4,421 (3,149 unique), threshold = 0.5 (default)

**Comment by MaxFrax** [comment]
# Report

All commands launched on soweego-2 VPS instance;
## Musician

### Evaluation

**Precision:**
mean =  0.9521950430004921
standard deviation = 0.0019505325818044495
**Recall:**
mean = 0.9094950755348116
standard deviation = 0.0010140158656438663
**F-score:**
mean = 0.9303547116359852
standard deviation = 0.001306918399658458

### Training

`python -m soweego linker train svm musicbrainz musician (launched from pipeline)`
model: /app/shared/musicbrainz_musician_svm_model.pkl, 1 KB

### Classification

`python -m soweego linker classify svm musicbrainz musician (launched from pipeline)`
total predictions: 86 430 (86 430 unique), threshold = 0.5 (default)

## Band

### Evaluation

Precision:
mean = 0.9078067352382353
standard deviation =0.002929691487500044
Recall:
mean = 0.7875059657273222
standard deviation = 0.003099500569805865
F-score:
mean = 0.8433831218218251
standard deviation = 0.0022776558108635898
## Training

`python -m soweego linker train svm musicbrainz band`
model: musicbrainz_band_svm_model.pkl, 1 KB
## Classification

`python -m soweego linker classify svm musicbrainz band`
total predictions: 18102 (17144 unique), threshold = 0.5 (default)

**Comment by MaxFrax** [comment]
# Performance comparison
We compare Naïve Bayes with SVM.

## Musician
- Precision: **+0.77%** (0.9521950430004921 - 0.9444080077302754 = 0,00778703527)
- Recall: **+5.43%** (0.9094950755348116 -  0.8551912065571845 = 0.05430386898)
- F-score: **+3.27%** (0.9303547116359852 - 0.8975842104582478 = 0.03277050118)

## Band
- Precision: **-8.89%** (0.9078067352382353 - 0.9967341074998514 = -0.08892737226)
- Recall: **+69,3%** (0.7875059657273222 - 0.09512493942864378 = 0.6923810263)
- F-score: **+66,97%** (0.8433831218218251 - 0.17365811404005033 = 0,6697250078)
