### ISSUE TITLE
Launch Naïve Bayes and SVM linkers over complete IMDb datasets

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#204]
INPUT: all datasets of all entities
- [x] evaluate;
- [x] train;
- [x] classify;
- [x] track progress & report. 

Corresponding CLI command examples:
```
python -m soweego linker evaluate nb imdb actor
python -m soweego linker train nb imdb actor
python -m soweego linker classify imdb actor /app/shared/imdb_nb_model.pkl
```

**Comment by tupini07** [comment]
The training process for the _Naive Bayes_ classifier was done on all `imdb` entities (_actor director musician producer writer_) and it completed without any issues.

**Comment by tupini07** [comment]
# Naive Bayes Report
* All commands launched on local docker instance.

## Writer
### Evaluation

Log: `20190329_imdb_writer_evaluation.log.bz2`

- Precision:
	- mean = 0.961372130318851
	- standard deviation = 0.002137514782853102
- Recall:
	- mean = 0.6605703532116651
	- standard deviation = 0.005168079021673254
- F-score:
	- mean = 0.7830675796661403
	- standard deviation = 0.003894471289444645

### Training
* `python -m soweego -l soweego DEBUG linker train nb imdb writer`
* log file: `20190329_imdb_writer_training.log.bz2`
* Wikidata dataset: **33,515** items 
* model: `imdb_writer_nb_model.pkl`, **1.9 KB**

### Classification
* `python -m soweego -l soweego DEBUG linker classify nb imdb writer`
* log file: `20190329_imdb_writer_classification.log.bz2`
* Wikidata dataset: **16,446** items
* total predictions: **2,241** (**2,226** unique), threshold = **0.5** (default)


## Director
### Evaluation

Log: `20190329_imdb_director_evaluation.log.bz2`

* Precision:
	* mean = 0.9585272249229119
	* standard deviation = 0.0023023566564076446
* Recall:
	* mean = 0.5410425582779812
	* standard deviation = 0.00588037556489547
* F-score:
	* mean = 0.6916568496948298
	* standard deviation = 0.005283906260169675

### Training
* `python -m soweego -l soweego DEBUG linker train nb imdb director`
* log file: `20190329_imdb_director_training.log.bz2`
* Wikidata dataset: **39,353** items
* model: `imdb_director_nb_model.pkl`, **1.9 KB**

### Classification
* `python -m soweego -l soweego DEBUG linker classify nb imdb director`
* log file: `20190329_imdb_director_classification.log.bz2`
* Wikidata dataset: **9,399** items
* total predictions: **2,063** (**1,023** unique), threshold = **0.5** (default)


## Actor
### Evaluation

Log: `20190329_imdb_actor_evaluation.log.bz2`

- Precision:
	- mean = 0.9639457933674478
	- standard deviation = 0.0012474709688274235
- Recall:
	- mean = 0.6649827728486299
	- standard deviation = 0.004162753170758487
- F-score:
	- mean = 0.7870195152407934
	- standard deviation = 0.0026578032831442795

### Training
* `python -m soweego -l soweego DEBUG linker train nb imdb actor`
* log file: `20190329_imdb_actor_training.log.bz2`
* Wikidata dataset: **156,279** items
* model: `imdb_actor_nb_model.pkl`, **1.9 KB**

### Classification
* `python -m soweego -l soweego DEBUG linker classify nb imdb actor`
* log file: `20190329_imdb_actor_classification.log.bz2`
* Wikidata dataset: **96,548** items
* total predictions: **24,953** (**12,381** unique), threshold = **0.5** (default)


## Musician
### Evaluation

Log: `20190329_imdb_writer_evaluation.log.bz2`

- Precision:
	- mean = 0.9552566313923295
	- standard deviation = 0.003329406565453846
- Recall:
	- mean = 0.6649083090290917
	- standard deviation = 0.009054633677097027
- F-score:
	- mean = 0.7840369025927727
	- standard deviation = 0.006891401746373005

### Training
* `python -m soweego -l soweego DEBUG linker train nb imdb musician`
* log file: `20190329_imdb_musician_training.log.bz2`
* Wikidata dataset: **40,327** items
* model: `imdb_musician_nb_model.pkl`, **1.9 KB**

### Classification
* `python -m soweego -l soweego DEBUG linker classify nb imdb musician`
* log file: `20190329_imdb_musician_classification.log.bz2`
* Wikidata dataset: **217,112** items
* total predictions: **22,785** (**11,176** unique), threshold = **0.5** (default)


## Producer
### Evaluation

Log: `20190329_imdb_producer_evaluation.log.bz2`

- Precision:
	- mean = 0.9608180130676593
	- standard deviation = 0.0030415050258804483
- Recall:
	- mean = 0.5697619459750551
	- standard deviation = 0.011751233423526937
- F-score:
	- mean = 0.7152622680052744
	- standard deviation = 0.009420170885759452

### Training
* `python -m soweego -l soweego DEBUG linker train nb imdb producer`
* log file: `20190329_imdb_producer_training.log.bz2`
* Wikidata dataset: **13,902** items
* model: `imdb_producer_nb_model.pkl`, **1.9 KB**

### Classification
* `python -m soweego -l soweego DEBUG linker classify nb imdb producer`
* log file: `20190329_imdb_producer_classification.log.bz2`
* Wikidata dataset: **2,251** items
* total predictions: **333** (**332** unique), threshold = **0.5** (default)

**Comment by tupini07** [comment]
# Report svm

## actor
### Evaluation

Log: `20190329_imdb_actor_evaluate_svm.log.bz2`

- Precision:
	- mean = 0.8919895419673496
	- standard deviation = 0.001738220041655084
- Recall:
	- mean = 0.8311788635413155
	- standard deviation = 0.002514467365466251
- F-score:
	- mean = 0.8605071385095282
	- standard deviation = 0.0011725279744974767

### Training
* `python -m soweego -l soweego DEBUG linker train svm imdb actor`
* log file: `20190329_imdb_actor_train_svm.log.bz2`
* Wikidata dataset: **15,6279** items
* model: `imdb_actor_svm_model.pkl`, **950 Bytes**

### Classification

* `python -m soweego -l soweego DEBUG linker classify svm imdb actor`
* log file: `20190329_imdb_actor_classify_svm.log.bz2`
* Wikidata dataset: **96,548** items
* total predictions: **31,252** (**31,157** unique), threshold = **0.5** (default)


## director
### Evaluation

Log: `20190329_imdb_director_evaluate_svm.log.bz2`

- Precision:
	- mean = 0.9096010617290695
	- standard deviation = 0.001966342557706831
- Recall:
	- mean = 0.815398808339239
	- standard deviation = 0.003840739223187446
- F-score:
	- mean = 0.8599221895018825
	- standard deviation = 0.0023492427693952815

### Training
* `python -m soweego -l soweego DEBUG linker train svm imdb director`
* log file: `20190329_imdb_director_train_svm.log.bz2`
* Wikidata dataset: **39,353** items
* model: `imdb_director_svm_model.pkl`, **950 Bytes**

### Classification

* `python -m soweego -l soweego DEBUG linker classify svm imdb director`
* log file: `20190329_imdb_director_classify_svm.log.bz2`
* Wikidata dataset: **9,399** items
* total predictions: **3,871** (**3863** unique), threshold = **0.5** (default)


## musician
### Evaluation

Log: `20190329_imdb_musician_evaluate_svm.log.bz2`

- Precision:
	- mean = 0.9171430212274021
	- standard deviation = 0.0050170137273117
- Recall:
	- mean = 0.7936840363413812
	- standard deviation = 0.002270486901085105
- F-score:
	- mean = 0.8509460150192277
	- standard deviation = 0.0014880567574300136

### Training
* `python -m soweego -l soweego DEBUG linker train svm imdb musician`
* log file: `20190329_imdb_musician_train_svm.log.bz2`
* Wikidata dataset: **40,327** items
* model: `imdb_musician_svm_model.pkl`, **950 Bytes**

### Classification

* `python -m soweego -l soweego DEBUG linker classify svm imdb musician`
* log file: `20190329_imdb_musician_classify_svm.log.bz2`
* Wikidata dataset: **21,7112** items
* total predictions: **35,761** (**35,545** unique), threshold = **0.5** (default)


## producer
### Evaluation

Log: `20190329_imdb_producer_evaluate_svm.log.bz2`

- Precision:
	- mean = 0.8904232074465378
	- standard deviation = 0.005308991927891873
- Recall:
	- mean = 0.7690963948109896
	- standard deviation = 0.008241899669296542
- F-score:
	- mean = 0.8252754249010541
	- standard deviation = 0.003495650120051015

### Training
* `python -m soweego -l soweego DEBUG linker train svm imdb producer`
* log file: `20190329_imdb_producer_train_svm.log.bz2`
* Wikidata dataset: **13,902** items
* model: `imdb_producer_svm_model.pkl`, **950 Bytes**

### Classification

* `python -m soweego -l soweego DEBUG linker classify svm imdb producer`
* log file: `20190329_imdb_producer_classify_svm.log.bz2`
* Wikidata dataset: **2,251** items
* total predictions: **1,060** (**1,059** unique), threshold = **0.5** (default)


## writer
### Evaluation

Log: `20190329_imdb_writer_evaluate_svm.log.bz2`

- Precision:
	- mean = 0.9247703874868695
	- standard deviation = 0.003467866566514575
- Recall:
	- mean = 0.8068102210103152
	- standard deviation = 0.004315701311707668
- F-score:
	- mean = 0.8617621580929498
	- standard deviation = 0.0027240595744515155

### Training
* `python -m soweego -l soweego DEBUG linker train svm imdb writer`
* log file: `20190329_imdb_writer_train_svm.log.bz2`
* Wikidata dataset: **33,515** items
* model: `imdb_writer_svm_model.pkl`, **950 Bytes**

### Classification

* `python -m soweego -l soweego DEBUG linker classify svm imdb writer`
* log file: `20190329_imdb_writer_classify_svm.log.bz2`
* Wikidata dataset: **16,446** items
* total predictions: **4,597** (**4,582** unique), threshold = **0.5** (default)

**Comment by tupini07** [comment]
# Performance comparison

Here we compare the results obtained with Naive Bayes https://github.com/Wikidata/soweego/issues/204#issuecomment-477964956 and SVM https://github.com/Wikidata/soweego/issues/204#issuecomment-478038363 :


## actor

- Precision: **-7.1** (0.8919895419673496 - 0.9639457933674478 = -0.0719562514000982)
- Recall: **+16.6** (0.8311788635413155 - 0.6649827728486299 = 0.1661960906926856)
- F-score: **+7.3** (0.8605071385095282 - 0.7870195152407934 = 0.07348762326873481)


## director

- Precision: **-4.8** (0.9096010617290695 - 0.9585272249229119 = -0.048926163193842354 )
- Recall: **+27.4** (0.815398808339239 - 0.5410425582779812 = 0.27435625006125774 )
- F-score: **+16.8** (0.8599221895018825 - 0.6916568496948298 = 0.16826533980705272 )


## musician

- Precision: **-3.8** (0.9171430212274021 - 0.9552566313923295 = -0.038113610164927425 )
- Recall: **+12.8** (0.7936840363413812 - 0.6649083090290917 = 0.12877572731228948 )
- F-score: **+6.6** (0.8509460150192277 - 0.7840369025927727 = 0.06690911242645503 )


## producer

- Precision: **-7.0** (0.8904232074465378 - 0.9608180130676593 = -0.07039480562112155 )
- Recall: **+19.9** (0.7690963948109896 - 0.5697619459750551 = 0.19933444883593443 )
- F-score: **+11.0** (0.8252754249010541 - 0.7152622680052744 = 0.11001315689577973 )


## writer

- Precision: **-3.6** (0.9247703874868695 - 0.961372130318851 = -0.03660174283198159 )
- Recall: **+14.6** (0.8068102210103152 - 0.6605703532116651 = 0.14623986779865006 )
- F-score: **+7.8** (0.8617621580929498 - 0.7830675796661403 = 0.07869457842680949 )
