### ISSUE TITLE
Baseline perfect name match should do bulk queries

### ISSUE THREAD

**Issue by MaxFrax** [Wikidata/soweego#205]
Currently, the Baseline perfect name match is really bad. It takes from 1 to 5 seconds per Wikidata entry to search into the database.
This is probably due to the fact that very often we hit the worst case, meaning that what we are looking for is missing.
Searching multiple entities at once would amortise the cost of the query.

Furthermore, the original implementation is good in an ideal context in which the connection to the database has no latency. Querying in bulks would amortize that cost too.

**Comment by marfox** [comment]
Adding a standard index on top of the name column should already improve the query execution time
