### ISSUE TITLE
Feature based on similar names

### ISSUE THREAD

**Issue by MaxFrax** [Wikidata/soweego#213]
Extract a similar-names feature from the dataset pair, to be implemented in workflow.extract_features.

It should be inspired by the baseline similar names match.

Other features implemented in `feature_extraction.py`

Useful docs:
https://recordlinkage.readthedocs.io/en/latest/ref-compare.html
https://recordlinkage.readthedocs.io/en/latest/ref-compare.html#user-defined-algorithms

**Comment by marfox** [comment]
Subtask of #214
