### ISSUE TITLE
Experiment with blocking techniques for classification

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#243]
Blocking can effectively _drive_ a classifier.

Blocking on relevant columns may have a big impact on precision (at the cost of recall).
We experienced this when blocking on Wikidata `birth_name` and Discogs `real_name`: great precision, low recall.

Currently blocking is only performed on the `NAME_TOKENS`

- [x] Implement generic perfect matching in OR
- [ ] try blocking on URLs
- [ ] try blocking on URL tokens
- [ ] try blocking on names
- [ ] try blocking on dates

**Comment by tupini07** [comment]
A list of _stopwords_ has been created for URLs, to use when blocking using `URL_TOKENS`. These stopwords include all tokens that appear in more that `0.00702%` of the URLs in our databse. This percentage was determined manually by doing the following and examining the output:

```python
```

**Comment by tupini07** [comment]
**Note:** I'll be adding results to this comment, as they become available

# Blocking on complete Names

## Musicbrainz musician

<details>
<summary>Classification distribution</summary>

![musicbrainz_musician_slp](https://user-images.githubusercontent.com/3422347/58316529-06339400-7e14-11e9-8ea4-d6c1ebf97c71.png)


</details>

Number preditions: 27949
Number confident: 6823



## Musicbrainz band

<details>
<summary>Classification distribution</summary>

![musicbrainz_band_slp](https://user-images.githubusercontent.com/3422347/58316544-0e8bcf00-7e14-11e9-8b14-75f7e51719e0.png)

</details>


Number preditions: 5142
Number confident: 1578

**Comment by marfox** [comment]
We finally kept the original blocking based on names and full-text index queries to the DB
