### ISSUE TITLE
Adding code style guideline

### ISSUE THREAD

**Issue by MaxFrax** [Wikidata/soweego#25]
In particular:

- For paths, no string concatenation but `os.path.join`
- Loading of resources should be done using `resources.get_data`
- Paths for Input should be set from `click.argument`
- Paths for Output should be set from `click.option`

**Comment by marfox** [comment]
See https://github.com/Wikidata/soweego/blob/master/CONTRIBUTING.md and https://soweego.readthedocs.io/en/latest/contribute.html
