### ISSUE TITLE
Handle QIDs with multiple positive samples

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#261]
The current implementation only considers 1 positive sample per QID.
Resolve `TODO` at `linker.train._build_positive_samples_index#92`.

**Comment by tupini07** [comment]
This is by how many items the IMDb dataset will be expanded if we consider QIDs with multiple positive samples: 

- Actor: 253
- Director: 80
- Writer: 46
- Musician: 48
- Producer: 26

Seeing that making this fix does not provide much extra data I'll leave this issue for later :smile:

**Comment by tupini07** [comment]
The functionality to expand the list of multiple positive samples has already been implemented in e299dc554f2518f81b7939c0598d37ecaa92b154 . However, the process seems to be crashing in: https://github.com/Wikidata/soweego/blob/e299dc554f2518f81b7939c0598d37ecaa92b154/soweego/linker/workflow.py#L181 

An exception is thrown saying that the number of `candidate_pairs` is not compatible with the index of `wikidata`. It might be something related with the fact that now the `wikidata` dataframe may contain more than one instance of a QID, but a more thorough investigation is needed. A possible _culprit_ can be `blocking.full_text_query_block`. Note that the process doesn't fail when there was no expansion of the positive samples (so, when there are no repeated QIDs in the dataframe)

**Comment by marfox** [comment]
@tupini07 , do you think we can close the issue and add the `wontfix` label?

**Comment by tupini07** [comment]
@marfox I think you're right. Some progress has been done in the [multiple-positive-samples](https://github.com/Wikidata/soweego/tree/multiple-positive-samples) banch, so I'll leave that in case this issue is going to be reopened in the future
