### ISSUE TITLE
Rule for MusicBrainz entities with a Wikidata URL

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#264]
MusicBrainz entities sometimes have a Wikidata URL: if so, the classification is already done on the target side, but it's currently ignored (treated as a standard URL feature).

- [ ] Add a rule that links MusicBrainz with Wikidata if the given MusicBrainz entity has a Wikidata URL;
- [ ] filter probabilistic links when a QID mismatches with the Wikidata URL from MusicBrainz.

**Comment by MaxFrax** [comment]
Running my filter against MusicBrainz SVM results, the following prediction changes happen: 
[prediction_changes.log.zip](https://github.com/Wikidata/soweego/files/3093412/prediction_changes.log.zip)

The following graph shows the distribution of the changes and explains why the SVM results quantity drops sensibly after the filtering.
![Musicbrainz prediction changes](https://user-images.githubusercontent.com/3145452/56347757-44121c80-61c5-11e9-9cd4-b9d8e5c93e85.jpg)

In the following comment, I'll post an analysis for Discogs as soon as I do one.
