### ISSUE TITLE
Do not populate the band table when a MusicBrainz entity type is unknown

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#265]
Based on the assessment of the uploaded statements as per #260, several errors were due to a Wikidata **band** being matched with a MusicBrainz **musician**.

I believe this is caused by the import process, which populates both tables when a MusicBrainz entity type is unknown.
This assumption should be verified, though.

**Comment by MaxFrax** [comment]
Do we have any kind of list of the incriminated errors? I would use that to check if the mistakes are fixed by changing the importer logic.
Maybe there's another way to verify the assumption that I'm missing.

**Comment by MaxFrax** [comment]
# Report

## Importer logic change

The former **band** types were `[ band, choir, orchestra, null, other ]` and the former **musician** types were `[ artist, character, null, other]`.
To fix the issue, entities of type `null` or `other` are discarded.

The following chart shows the difference between each MusicBrainz table.

[Chart.pdf](https://github.com/Wikidata/soweego/files/3047111/Chart.pdf)
![Chart](https://user-images.githubusercontent.com/3145452/55616045-3b672280-5791-11e9-976b-43907b67b4e2.jpg)

## Test

I have extracted from [Hjfocs contributions](https://www.wikidata.org/w/index.php?title=Special:Contributions/Hjfocs&offset=&limit=500&target=Hjfocs) into [mistakes.csv.zip](https://github.com/Wikidata/soweego/files/3047145/mistakes.csv.zip) the mistakes he found.
As @marfox (aka Hjfocs) said, `‎Removed claim: MusicBrainz artist ID (P434)` on April 1st 2019 are the mistakes made from sample `musicbrainz_band_nb_sample.json`, while the ones on April 2nd are the mistakes made from sample `musicbrainz_musician_svm_sample.json`.

TO COMPLETE

**Comment by marfox** [comment]
Thank you @MaxFrax for the in-depth report. Although the test might not be statistically significant, I still believe that the main goal is achieved.
