### ISSUE TITLE
Too many SPARQL queries sent when gathering the occupation tree

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#273]
The Wikidata SPARQL endpoint responded with a `429` HTTP error code when retrieving occupation subclasses for **IMDb director**. The following error message is emitted after `workflow.extract_features#135`:
```
429 Too Many Requests - Query: SELECT DISTINCT ?item WHERE { ?item wdt:P279* wd:Q7042855 . }
```

The command that hit this is `python -m soweego linker classify imdb director`, launched in the `soweego-1` VPS instance.

**Comment by tupini07** [comment]
It seems that the root of this issue was the `OccupationQidSet` feature extractor, which was being executed in multiple threads and was not managing this concurrency, so the tree _super-classes_ and _sub-classes_ was being calculated once for each thread.
