### ISSUE TITLE
Project does not fully support musical work entities

### ISSUE THREAD

**Issue by MaxFrax** [Wikidata/soweego#328]
In many places in the project `target_database.get_person_pid` is used. 
Tough, only `mix_n_match_client.py` handles that maybe the entity could be a musical work. In which case `target_database.get_work_pid` is called.

My proposal is to merge the two getters into a single function which, given the entity type as input, returns the right PID.
This can be achieved by moving `mix_n_match_client.ENTITY_TYPES` etc. into `target_database.py`.

**Comment by marfox** [comment]
Done, we should now fix the usage of `target_database.get_person_id` in:
- [x] ingestor;
- [ ] validator;
- [ ] linker.

**Comment by marfox** [comment]
Done, we should now fix the usage of `target_database.get_person_id` in:
- [x] ingestor;
- [x] validator;
- [ ] linker.
