### ISSUE TITLE
Provide human-readable labels and descriptions in Mix'n'match catalogs

### ISSUE THREAD

**Issue by fokky** [Wikidata/soweego#364]
I would be very happy to lend a hand with manual matching in the various Mix'n'match catalogs provided via the soweego project. I'm a very active Mix'n'match user.

However, the current soweego Mix'n'match catalogs are not easy to use, as they provide no clear human-readable labels and descriptions. I would suggest putting some effort in making these available in Mix'n'match, next to the soweego confidence scores.

A pleasant and usable catalog in MnM [looks like this](https://tools.wmflabs.org/mix-n-match/#/list/2760/auto), for instance - inviting active participation and manual matching:
![image](https://user-images.githubusercontent.com/9881645/64124347-15c56000-cda7-11e9-8262-1bd43d32aea9.png)
Note that there is a human-readable label for the item in the original catalog, that allows immediate comparison with the Wikidata label; and there is a human-readable description snippet that allows direct comparison with the automated description from Wikidata.

Compare this to a [soweego catalog](https://tools.wmflabs.org/mix-n-match/#/list/2733/auto):
![image](https://user-images.githubusercontent.com/9881645/64125084-0f37e800-cda9-11e9-8d08-076657b5c752.png)
The user first needs to click and open a tab to check each item in MusicBrainz, unlike in the previous example. This makes matching much more tedious. I would like to ask that the IDs here would be replaced with the actual item names from the external database, and that a short informative description would be scraped from the source database that can be checked immediately in addition to the soweego score.

**Comment by marfox** [comment]
Thanks a lot @fokky for your detailed feedback, super appreciated.
This is a known issue, see #325 .
I'm closing yours as a duplicate, add the description field request and raise the priority to #325 , which was originally out of the first project grant time span.
