### ISSUE TITLE
No display of the Wikidata bot in the Sphinx documentation

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#387]
See https://soweego.readthedocs.io/en/latest/ingester.html#module-soweego.ingester
Docstrings seem there: https://github.com/Wikidata/soweego/blob/020a792add1ea2572358da671c7900222a146966/soweego/ingester/wikidata_bot.py

**Comment by tupini07** [comment]
@marfox I tried building the documentation locally and I also experienced the same issue you mentioned (`ingester.wikidata_bot` has no module documentation). 

However, while building the doc I noticed that Sphinx was complaining about it not being able to find some dependencies. Once I installed the missing dependencies the documentation got generated correctly.

Do you know where are we generating the documentation for https://soweego.readthedocs.io/ ? Is it with TravisCI?

I think the first step is to check whether the env building the doc has the required dependencies from `requirements.txt` :smile:

**Comment by marfox** [comment]
Thanks a lot for your reaction!
The documentation build happens at readthedocs.org, see for instance
https://readthedocs.org/projects/soweego/builds/10741570/

If I remember correctly, a new build is triggered when the master branch is
updated.

I think I've never touched the readthedocs build script, so I guess we
should have a look there.

Il mer 5 mag 2021, 01:10 Andrea Tupini ***@***.***> ha
scritto:

**Comment by marfox** [comment]
Fixed
