### ISSUE TITLE
Docker configuration

### ISSUE THREAD

**Issue by MaxFrax** [Wikidata/soweego#49]
The whole project should work in a virtual environment like Docker

**Comment by marfox** [comment]
This is both needed in the long term, i.e., final packaging of the project, and in the short term to test the importer with less pain

**Comment by MaxFrax** [comment]
@marfox Should I create a [Docker Compose](https://docs.docker.com/compose/) with just the MariaDB's [container](https://www.docker.com/resources/what-container) or should I create a container for the whole soweego cli and add it to the composer too?
@EdoardoLenzi9 I'd like to know if you agree with me too.

**Comment by marfox** [comment]
I assume it's closed since @MaxFrax moved it to `done`, see https://github.com/Wikidata/soweego/issues/49#event-1919837034
