### ISSUE TITLE
Match MusicBrainz releases

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#56]
Currently, only **37** out of **256k** albums in Wikidata have a MusicBrainz identifier:
```
SELECT (COUNT(DISTINCT ?item) AS ?count) WHERE { ?item wdt:P31/wdt:P279* wd:Q482994 ; wdt:P434 ?identifier . }
```
Investigate how we could leverage the album data in MusicBrainz to **both** populate album identifiers and _performer_ statements, like:
[Animals](https://www.wikidata.org/wiki/Q206216), [performer](https://www.wikidata.org/wiki/Property:P175), [Pink Floyd](https://www.wikidata.org/wiki/Q2306)

**Comment by MaxFrax** [comment]
We are also interested to extract the information about who created that release.

**Comment by MaxFrax** [comment]
Your query was wrong, [P434](https://www.wikidata.org/wiki/Property:P434) is meant to link to MusicBrainz artists.

**Comment by MaxFrax** [comment]
Just counting by (MusicBrainz release group id P:436)[https://www.wikidata.org/wiki/Property:P436]
gives coverage of `87170/251658` = 34%.

Release group is not the only id that works on albums, it's a pretty complex area.

**Comment by marfox** [comment]
Thanks for the extra pair of eyes, @MaxFrax !
I still believe that 2/3 of the album items is still worth the effort.
Said that, the most fruitful outcome is to populate `performer` statements, so I would suggest to focus on that task.
