### ISSUE TITLE
Musicbrainz - extract ISNI code from artist attributes

### ISSUE THREAD

**Issue by MaxFrax** [Wikidata/soweego#85]
*Notes:*
Only the id part of ISNI is stored in Musicbrainz.
While importing this id should be translated in a url by inserting it in the formatter given from Wikidata.

**Comment by MaxFrax** [comment]
Wikidata gives us formatter url and third party formatter url, we need to understand which one is the right one.

**Comment by marfox** [comment]
I assume it's closed since @MaxFrax moved it to `done`, see https://github.com/Wikidata/soweego/issues/85#event-1965464597
