### ISSUE TITLE
Levenshtein distance name matcher

### ISSUE THREAD

**Issue by marfox** [Wikidata/soweego#9]
~~- [ ] Pick the best implementation that fits our use case here: https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#Python;~~
- [ ] use [jellyfish](https://github.com/jamesturk/jellyfish);
- [ ] for each full name of a target identifier, compute the Levenshtein edit distance against all Wikidata item labels.

**Comment by MaxFrax** [comment]
Why don't we use it for links too?
