### ISSUE TITLE
Importer implementation for IMDb

### ISSUE THREAD

**Issue by MaxFrax** [Wikidata/soweego#99]
Follow the guide in the [wiki](https://github.com/Wikidata/soweego/wiki/Import-a-new-database) to add [IMDb](http://imdb.com/).

**Condition of satisfaction**:
1. After the computation of `soweego importer import_catalog` of the new database, a new fulfilled table will be available in the database.

**Comment by MaxFrax** [comment]
@marfox any suggestion about the target database?

**Comment by marfox** [comment]
> @marfox any suggestion about the target database?
It would be great to have IMDb imported

**Comment by MaxFrax** [comment]
@fedriz good work!
